tagline: Monthly Python talks in the North-East of England
about:
  <p>We're a group who promote the use of the Python programming language.
  We organise monthly meet-ups and other community events and aim to be a focal
  part of the wider Python community in the North East.</p>
  <p>We're also super friendly - beginners and non-Pythonistas are especially welcome
  to our events and to participate in our discussions.</p>
address:
  - Campus North
  - 5 Carliol Square
  - Newcastle upon Tyne
  - NE1 6UF
