tagline: Monthly Python talks in the north-east of England
about: <p>We're a group who promote the use of the Python programming language.
  We organise monthly meet-ups and other community events and aim to be a focal
  part of the wider Python community in the North East.</p>
  <p>We're also super friendly&mdash;beginners and non-Pythonistas are especially welcome
  to our events and to participate in our discussions.</p>
address:
  - The Core
  - Science Central
  - Bath Ln
  - Newcastle upon Tyne
  - NE4 5TF
domain: https://www.pythonnortheast.com
start_time: 1800
end_time: 2000
event_email: info@pythonnortheast.com
contact_email: info@pythonnortheast.com
twitter: https://twitter.com/pythonnortheast
